name: photo_manager_env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - dlib
  - mtcnn
  - opencv
  - face_recognition
  - pillow
  - numpy
  - scikit-learn
  - matplotlib
  - piexif
  - pytest