name: Face Recognition CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: Set up Miniconda with mamba
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-variant: miniforge3
        python-version: ${{ matrix.python-version }}
        auto-update-conda: true
        channels: conda-forge, defaults
        activate-environment: photo_manager_env
        environment-file: photo_manager_env.yml
        use-mamba: true

    - name: Install mamba and dependencies
      run: |
        conda install mamba -n base -c conda-forge
        mamba env update -f photo_manager_env.yml
        conda clean -a -y

    - name: Check conda installation
      run: |
        conda info
        conda list
        conda env list

    - name: Run photo manager script tests
      shell: bash -l {0}
      run: |
        source $(conda info --base)/etc/profile.d/conda.sh
        conda activate photo_manager_env
        python -m unittest discover -s tests