name: Photo Manager CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Miniconda with mamba
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-variant: mambaforge
        python-version: ${{ matrix.python-version }}
        auto-update-conda: true
        channels: conda-forge
        activate-environment: photo_manager_env
        environment-file: photo_manager_env.yml
        use-mamba: true

    - name: Install dependencies
      run: |
        mamba env update -f photo_manager_env.yml
        conda clean -a -y

    - name: Check conda installation
      run: |
        conda info
        conda list
        conda env list
        cat $(conda info --base)/.conda/environments.txt

    - name: Run photo manager script tests
      run: |
        source activate photo_manager_env
        python -m unittest discover -s tests